CREATE DATABASE RUBIKCUBE_TIMER
USE RUBIKCUBE_TIMER
CREATE TABLE USUARIO
(
	ID_US INT IDENTITY (20220, 1),
	NOME VARCHAR (50) NOT NULL,
	LOGIN_US VARCHAR (30) NOT NULL,
	SENHA VARCHAR (32) NOT NULL,
	CONSTRAINT PK_ID_US PRIMARY KEY (ID_US)
)

CREATE TABLE RECORD
(
	ID_REC INT NOT NULL IDENTITY,
	ID_US INT NOT NULL,
	TIPO_CUBO INT NOT NULL,
	MELHOR_TEMPO VARCHAR (9) NOT NULL,
	DATA_REC VARCHAR (10) NOT NULL,
	CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_US) REFERENCES USUARIO (ID_US),
	CONSTRAINT PK_ID_REC PRIMARY KEY (ID_REC)
)

SELECT * FROM RECORD
SELECT * FROM USUARIO